# Generated by Django 5.1.1 on 2024-12-19 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='city',
            new_name='fullname',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='first_name',
            new_name='plan',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='last_name',
        ),
        migrations.AddField(
            model_name='payment',
            name='phone',
            field=models.CharField(default='N/A', max_length=15),
        ),
    ]
